"""empty message

Revision ID: 0874d097e15d
Revises: 84fcfb50a5b0
Create Date: 2025-04-22 23:05:29.794964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0874d097e15d'
down_revision = '84fcfb50a5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'name')
    )
    op.create_table('folder_documents',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'document_id')
    )
    op.create_table('folder_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('documents_folder_id_fkey', type_='foreignkey')
        batch_op.drop_column('folder_id')
        batch_op.drop_column('tags')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_oauth_google_id_key', type_='unique')
        batch_op.drop_column('oauth_google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_google_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_oauth_google_id_key', ['oauth_google_id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('documents_folder_id_fkey', 'folders', ['folder_id'], ['id'])

    op.drop_table('folder_permissions')
    op.drop_table('folder_documents')
    op.drop_table('document_tags')
    # ### end Alembic commands ###
