"""empty message

Revision ID: 84fcfb50a5b0
Revises: c00e552ebf03
Create Date: 2025-04-22 18:54:37.351909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fcfb50a5b0'
down_revision = 'c00e552ebf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_google_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['oauth_google_id'])

    # ### end Alembic commands ###
    
    # Manually add code to drop document_folders table if it exists
    op.execute("""
    DROP TABLE IF EXISTS document_folders CASCADE;
    """)
    
    # Ensure documents table has folder_id foreign key
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'documents' AND column_name = 'folder_id'
        ) THEN
            ALTER TABLE documents ADD COLUMN folder_id INTEGER REFERENCES folders(id);
        END IF;
    END
    $$;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('oauth_google_id')

    # ### end Alembic commands ###
