"""simplified data tables even more2

Revision ID: c00e552ebf03
Revises: 6a2b745a999f
Create Date: 2025-04-08 20:31:46.968103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c00e552ebf03'
down_revision = '6a2b745a999f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_folders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_folders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_folders_document_id_fkey'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name='document_folders_folder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_folders_pkey'),
    sa.UniqueConstraint('folder_id', 'document_id', name='uix_document_folder')
    )
    # ### end Alembic commands ###
